name: davi
description: A full customized dataview that builds the cells on demand. Focused on Web/Desktop Applications. Bidirectional scroll bars. (DataTable, Data Table, Data View)
version: 4.0.0-rc.2
repository: https://github.com/caduandrade/davi_flutter

screenshots:
  - description: Example of Davi's implementation
    path: screenshots/screenshot1.png
  - description: Cell bar layout design
    path: screenshots/screenshot2.png
  - description: Custom cell configuration example
    path: screenshots/screenshot3.png
  - description: Cell merging feature demonstration
    path: screenshots/screenshot4.png

topics:
  - data
  - dataview
  - view
  - datatable
  - table

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  axis_layout: ^1.0.1
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true