import 'dart:math' as math;

enum Skill {
  favorite,
  grade,
  pets,
  science,
  shield,
  wbSunny,
  flashOn,
  adjust,
  flare,
  filterVintage,
  workspaces,
  cloud,
  acUnit
}

extension on Skill {
  int compareTo(Skill other) => index.compareTo(other.index);
}

class Character {
  Character(
      {required this.name,
      required this.male,
      required this.age,
      required this.race,
      required this.gold,
      required this.cls,
      required this.level,
      required this.strength,
      required this.intelligence,
      required this.dexterity,
      required this.life,
      required this.mana,
      required this.skills});

  final String name;
  final bool male;
  final int age;
  final String race;
  final String cls;
  final double? gold;
  final int level;
  final int strength;
  final int intelligence;
  final int dexterity;
  final int mana;
  final int life;
  final List<Skill> skills;

  bool get female => !male;

  static const List<String> _races = [
    'Dwarf',
    'Elf',
    'Hobbit',
    'Human',
    'Goblin',
    'Golem',
    'Orc',
    'Troll',
    'Angel',
    'Elemental',
    'Undead'
  ];

  static const List<String> _classes = [
    'Warrior',
    'Assassin',
    'Mage',
    'Ranger',
    'Berserker',
    'Cleric',
    'Necromancer',
    'Summoner',
    'Bard',
    'Monk',
    'Paladin',
    'Druid'
  ];

  static const List<String> _females = [
    "Lillian Richardson",
    "Marilyn Bell",
    "Karen Coleman",
    "Linda Parker",
    "Shirley Perry",
    "Irene Baker",
    "Nicole Kelly",
    "Stephanie Hughes",
    "Amanda Walker",
    "Sandra Cook",
    "Joyce Jones",
    "Evelyn Adams",
    "Andrea Martinez",
    "Bonnie Foster",
    "Cheryl Williams",
    "Jennifer Murphy",
    "Sara Gonzales",
    "Lori Green",
    "Beverly Roberts",
    "Carolyn Anderson",
    "Jessica James",
    "Mildred Edwards",
    "Janice Jenkins",
    "Sharon Young",
    "Wanda Collins",
    "Sarah Morris",
    "Julie Sanders",
    "Ruby Moore",
    "Doris Scott",
    "Patricia Rogers",
    "Rachel Lewis",
    "Helen Evans",
    "Susan Bennett",
    "Elizabeth Jackson",
    "Anna Wright",
    "Pamela Patterson",
    "Margaret Wood",
    "Amy Hill",
    "Angela Howard",
    "Gloria Flores",
    "Ann Bryant",
    "Janet Perez",
    "Mary Hall",
    "Catherine Gray",
    "Judith Russell",
    "Anne Hernandez",
    "Diane Rodriguez",
    "Joan Nelson",
    "Betty Watson",
    "Barbara Carter",
    "Brenda Simmons",
    "Jean Ramirez",
    "Rose King",
    "Lois Alexander",
    "Kelly Stewart",
    "Heather Harris",
    "Paula Peterson",
    "Rebecca Thomas",
    "Kathleen Reed",
    "Ashley Griffin",
    "Emily Miller",
    "Katherine Powell",
    "Phyllis Robinson",
    "Kathryn Henderson",
    "Deborah Campbell",
    "Donna Diaz",
    "Denise Morgan",
    "Kimberly Turner",
    "Christine Clark",
    "Diana Garcia",
    "Norma Martin",
    "Cynthia White",
    "Michelle Cox",
    "Melissa Brooks",
    "Jacqueline Bailey",
    "Maria Ross",
    "Theresa Davis",
    "Dorothy Phillips",
    "Debra Thompson",
    "Tammy Smith",
    "Annie Ward",
    "Louise Torres",
    "Ruth Butler",
    "Judy Taylor",
    "Tina Cooper",
    "Lisa Washington",
    "Virginia Wilson",
    "Christina Long",
    "Kathy Lopez",
    "Jane Johnson",
    "Laura Allen",
    "Marie Gonzalez",
    "Nancy Barnes",
    "Alice Mitchell",
    "Julia Sanchez",
    "Frances Rivera",
    "Martha Lee",
    "Carol Price",
    "Teresa Brown",
    "Cira Crocker",
    "Mertie Smallwood",
    "Serina Schmitz",
    "Doreatha Mathews",
    "Lakita Avery",
    "Andree Lenz",
    "Spring Crosby",
    "Vanetta Sisco",
    "Cinderella Mock",
    "Joleen Ledesma",
    "Maire Ellington",
    "Valarie Fish",
    "Christian Schwab",
    "Violette Guidry",
    "Myrtice Hagen",
    "Linnie Gomes",
    "Corinna Boothe",
    "Kyle Morse",
    "Lesli Shepherd",
    "Annice Mcintosh",
    "Carma Zamora",
    "Fidela Woodbury",
    "Lidia Finnegan",
    "Cheri Villasenor",
    "Hildred Duggan",
    "Iraida Birch",
    "Evita Rohr",
    "Billye Miranda",
    "Bronwyn Mcneely",
    "Charline Magee",
    "Jackqueline Lanham",
    "Shonda Witte",
    "Karol Fair",
    "Margy Rader",
    "Lavonia Matney",
    "Francisco Rinaldi",
    "Malia Bedard",
    "Joslyn Coyne",
    "Shannan Goldberg",
    "Carolann Talley",
    "Tanja Thurston",
    "Julian Carey",
    "Sari Malley",
    "Lynna Milliken",
    "Mirtha Ferris",
    "Hallie Ferraro",
    "Keri Koch",
    "Slyvia Leary",
    "Florrie Bullock",
    "Deane Morrow",
  ];

  static const List<String> _males = [
    "Benjamin Gonzalez",
    "Todd Edwards",
    "Scott Cook",
    "Jose Taylor",
    "Johnny Simmons",
    "Victor Brooks",
    "Roy Hughes",
    "Keith Washington",
    "Joshua Jones",
    "Louis Evans",
    "Randy Scott",
    "Brian White",
    "Brandon Cox",
    "Ernest Gray",
    "Larry Jackson",
    "Bobby Richardson",
    "Steven Parker",
    "Richard Smith",
    "James Hernandez",
    "Philip Lopez",
    "Alan Harris",
    "Fred Morris",
    "Charles Garcia",
    "Howard Allen",
    "Harry Thomas",
    "Carl Martinez",
    "Jonathan Howard",
    "Jesse Price",
    "Paul Powell",
    "Matthew Griffin",
    "Timothy Nelson",
    "Raymond Morgan",
    "Adam Perez",
    "Lawrence Young",
    "Joe Ross",
    "Juan Davis",
    "Ryan Turner",
    "Craig Bailey",
    "Nicholas Green",
    "Michael Diaz",
    "William Lee",
    "Wayne Ramirez",
    "Aaron Bryant",
    "Ronald Johnson",
    "Mark Long",
    "Justin Murphy",
    "George Patterson",
    "Kevin Moore",
    "Roger Clark",
    "Willie Gonzales",
    "Stephen Wilson",
    "Jason Kelly",
    "Steve Rivera",
    "Donald Cooper",
    "Billy Sanders",
    "Gregory Walker",
    "Russell Hall",
    "Jerry Campbell",
    "Terry Thompson",
    "Carlos Martin",
    "Martin Robinson",
    "Frank Anderson",
    "John Rodriguez",
    "Joseph Roberts",
    "Chris Bell",
    "Kenneth Sanchez",
    "Edward Mitchell",
    "Jimmy Brown",
    "Jeremy Miller",
    "Ralph Coleman",
    "Sean Perry",
    "Thomas Foster",
    "Gerald Hill",
    "Henry Bennett",
    "Jack Carter",
    "Bruce Wright",
    "Arthur Collins",
    "Gary Russell",
    "Jeffrey Peterson",
    "Christopher Jenkins",
    "Eugene Stewart",
    "David Wood",
    "Phillip Adams",
    "Clarence Alexander",
    "Eric Butler",
    "Robert Flores",
    "Shawn James",
    "Samuel King",
    "Albert Baker",
    "Douglas Lewis",
    "Earl Williams",
    "Daniel Rogers",
    "Harold Torres",
    "Andrew Watson",
    "Anthony Ward",
    "Dennis Reed",
    "Walter Phillips",
    "Peter Henderson",
    "Patrick Barnes",
    "Royce Whittington",
    "Gino Grubbs",
    "Britt Sauer",
    "Russ Bertram",
    "Ezequiel Redd",
    "Whitney Chadwick",
    "Carmine Plante",
    "Lesley Clements",
    "King Pemberton",
    "Gaston Franz",
    "Marcellus Lapointe",
    "Riley Moeller",
    "Reinaldo Kraus",
    "Kasey Gold",
    "Olen Hankins",
    "Dewitt Andersen",
    "Emory Parson",
    "Ferdinand Rash",
    "Alphonse Shephard",
    "Freddy Prescott",
    "Jae Connors",
    "Dario Lyon",
    "Edmundo Razo",
    "Blair Meek",
    "Dong Zarate",
    "Danial Whitmore",
    "Boyce Currie",
    "Val Robins",
    "Monte Kruse",
    "Loyd Bartholomew",
    "Benedict Provost",
    "Jarrett Noonan",
    "Logan Dabney",
    "Raymundo Burrell",
    "Donovan Reddy",
    "Earle Polk",
    "Jamal Timmons",
    "Shayne Chin",
    "Werner Peel",
    "Maximo Crutchfield",
    "Carey Romano",
    "Lyman Dugger",
    "Cornell Boyer",
    "Chang Yoon",
    "Hunter Ott",
    "Gavin Shannon",
    "Toney Greenberg",
    "Delmar Huffman",
    "Landon Morey",
    "Reid Oakley",
  ];

  static List<Character> loadCharacters() {
    math.Random random = math.Random();
    List<Character> list = [];
    for (String name in _females) {
      list.add(_character(name: name, male: false, random: random));
    }
    for (String name in _males) {
      list.add(_character(name: name, male: true, random: random));
    }
    list.shuffle();
    return list;
  }

  static Character _character(
      {required String name, required bool male, required math.Random random}) {
    String race = _races[random.nextInt(_races.length)];
    int age = 20 + random.nextInt(80);
    String cls = _classes[random.nextInt(_classes.length)];
    int level = 1 + (random.nextInt(100) * random.nextDouble()).round();
    int strength =
        math.max(level + random.nextInt(100) - random.nextInt(20), 10);
    int intelligence =
        math.max(level + random.nextInt(100) - random.nextInt(20), 10);
    int dexterity =
        math.max(level + random.nextInt(100) - random.nextInt(20), 10);
    int mana = level + random.nextInt(500);
    int life = level + random.nextInt(5000);
    double? gold =
        life % 3 == 0 ? null : random.nextInt(500000) * random.nextDouble();

    Set<Skill> uniqueSkills = {};
    int skillsCount = random.nextInt(4);
    for (int i = 0; i < skillsCount; i++) {
      uniqueSkills.add(Skill.values[random.nextInt(Skill.values.length)]);
    }
    List<Skill> skills = uniqueSkills.toList();
    skills.sort((a, b) => a.compareTo(b));

    return Character(
        cls: cls,
        name: name,
        race: race,
        age: age,
        male: male,
        gold: gold,
        level: level,
        strength: strength,
        intelligence: intelligence,
        dexterity: dexterity,
        life: life,
        mana: mana,
        skills: skills);
  }
}
